spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:

decorator:
  datasource:
    p6spy:
      enable-logging: true