spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    driver-class-name: org.h2.Driver
    username: sa
    password:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      tracing:
        include-parameter-values: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
